### ISSUE TITLE
System.Windows.FrameworkElement.Style exception

### ISSUE THREAD

**Issue by DJCALIEND** [aidan-g/FoxTunes#42]
Hi

Thanks for your software.

I have a System.Windows.FrameworkElement.Style exception when I want to lauch FoxTunes.Launcher.exe.

In the Application Event Viewer I have :

Nom de l’application défaillante FoxTunes.Launcher.exe, version : 1.0.0.0, horodatage : 0xf2683082
Nom du module défaillant : KERNELBASE.dll, version : 10.0.17134.1184, horodatage : 0xda43ec6b
Code d’exception : 0xe0434352
Décalage d’erreur : 0x00114622
ID du processus défaillant : 0x1648
Heure de début de l’application défaillante : 0x01d5ba4df709aa33
Chemin d’accès de l’application défaillante : C:\Users\xxxx\Downloads\FoxTunes-2.0.7-net461\FoxTunes.Launcher.exe
Chemin d’accès du module défaillant: C:\WINDOWS\System32\KERNELBASE.dll
ID de rapport : 46151400-723e-47b9-b8d0-c8418f4dac4d
Nom complet du package défaillant : 
ID de l’application relative au package défaillant : 

Application : FoxTunes.Launcher.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.FormatException
   à System.Number.ParseDouble(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
   à System.Windows.Markup.XamlGridLengthSerializer.FromString(System.String, System.Globalization.CultureInfo, Double ByRef, System.Windows.GridUnitType ByRef)
   à System.Windows.GridLengthConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext, System.Globalization.CultureInfo, System.Object)
   à FoxTunes.ViewModel.GridLengthConverter.Convert(System.Object, System.Type, System.Object, System.Globalization.CultureInfo)
   à System.Windows.Data.BindingExpression.TransferValue(System.Object, Boolean)
   à System.Windows.Data.BindingExpression.Activate(System.Object)
   à System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt)
   à System.Windows.Data.BindingExpression.AttachOverride(System.Windows.DependencyObject, System.Windows.DependencyProperty)
   à System.Windows.Data.BindingExpressionBase.OnAttach(System.Windows.DependencyObject, System.Windows.DependencyProperty)
   à System.Windows.StyleHelper.GetInstanceValue(System.Windows.UncommonField`1<System.Collections.Specialized.HybridDictionary[]>, System.Windows.DependencyObject, System.Windows.FrameworkElement, System.Windows.FrameworkContentElement, Int32, System.Windows.DependencyProperty, Int32, System.Windows.EffectiveValueEntry ByRef)
   à System.Windows.StyleHelper.GetChildValueHelper(System.Windows.UncommonField`1<System.Collections.Specialized.HybridDictionary[]>, MS.Utility.ItemStructList`1<System.Windows.ChildValueLookup> ByRef, System.Windows.DependencyProperty, System.Windows.DependencyObject, MS.Internal.FrameworkObject, Int32, Boolean, System.Windows.EffectiveValueEntry ByRef, System.Windows.ValueLookupType ByRef, System.Windows.FrameworkElementFactory)
   à System.Windows.StyleHelper.GetChildValue(System.Windows.UncommonField`1<System.Collections.Specialized.HybridDictionary[]>, System.Windows.DependencyObject, Int32, MS.Internal.FrameworkObject, System.Windows.DependencyProperty, MS.Utility.FrugalStructList`1<System.Windows.ChildRecord> ByRef, System.Windows.EffectiveValueEntry ByRef, System.Windows.ValueLookupType ByRef, System.Windows.FrameworkElementFactory)
   à System.Windows.StyleHelper.GetValueFromStyleOrTemplate(MS.Internal.FrameworkObject, System.Windows.DependencyProperty, System.Windows.EffectiveValueEntry ByRef)
   à System.Windows.StyleHelper.ApplyStyleOrTemplateValue(MS.Internal.FrameworkObject, System.Windows.DependencyProperty)
   à System.Windows.StyleHelper.InvalidateContainerDependents(System.Windows.DependencyObject, MS.Utility.FrugalStructList`1<System.Windows.ContainerDependent> ByRef, MS.Utility.FrugalStructList`1<System.Windows.ContainerDependent> ByRef, MS.Utility.FrugalStructList`1<System.Windows.ContainerDependent> ByRef)
   à System.Windows.StyleHelper.DoStyleInvalidations(System.Windows.FrameworkElement, System.Windows.FrameworkContentElement, System.Windows.Style, System.Windows.Style)
   à System.Windows.FrameworkContentElement.OnStyleChanged(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   à System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   à System.Windows.FrameworkContentElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   à System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
   à System.Windows.DependencyObject.UpdateEffectiveValue(System.Windows.EntryIndex, System.Windows.DependencyProperty, System.Windows.PropertyMetadata, System.Windows.EffectiveValueEntry, System.Windows.EffectiveValueEntry ByRef, Boolean, Boolean, System.Windows.OperationType)
   à System.Windows.DependencyObject.SetValueCommon(System.Windows.DependencyProperty, System.Object, System.Windows.PropertyMetadata, Boolean, Boolean, System.Windows.OperationType, Boolean)
   à System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(System.Object, System.Object)
   à MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(System.Xaml.XamlMember, System.Object, System.Object)
   à MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(System.Object, System.Xaml.XamlMember, System.Object)

Informations sur l'exception : System.Windows.Markup.XamlParseException
   à System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   à System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   à System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   à System.Windows.Application.LoadComponent(System.Object, System.Uri)
   à FoxTunes.MainWindow.InitializeComponent()
   à FoxTunes.MainWindow..ctor()
   à FoxTunes.Windows+<>c.<Reset>b__59_0()
   à System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CreateValue()
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Value()
   à FoxTunes.Windows.get_MainWindow()
   à FoxTunes.WindowsUserInterface.Show()
   à FoxTunes.Launcher.Program.Main(System.String[])

I can reproduce this error with another computer (Windows 10 1909 fully patched).

Have you any idee ? 
Thanks a lot for your reply.

**Comment by aidan-g** [comment]
Hmm, not sure. I did test against windows 10 although it may have been out
of date. I will have a look today.

**Comment by aidan-g** [comment]
Could you try the "minimal" and "net40" packages please?

**Comment by DJCALIEND** [comment]
Yes it already done and it's the same thing. I Have the same thing with olders version of FoxTunes.

**Comment by aidan-g** [comment]
I think it's a localization problem, I've never tested on non english windows. Still investigating.

**Comment by aidan-g** [comment]
Do you have a user.config in Local\FoxTunes.Launcher\FoxTunes.Launcher.exe_Url_ .... something ... \1.0.0.0? What is the content?

**Comment by DJCALIEND** [comment]
In C:\Users\myname\AppData\Local I have not a FoxTunes.Launcher folder !!!

**Comment by aidan-g** [comment]
It's OK, I have managed to reproduce the error by setting a French system locale.

**Comment by aidan-g** [comment]
Try replacing your FoxTunes.UI.Windows.dll with this one

[FoxTunes.UI.Windows.zip](https://github.com/aidan-g/FoxTunes/files/3998304/FoxTunes.UI.Windows.zip)

**Comment by DJCALIEND** [comment]
Perfect 👍 . Bug fixed. Thanks a lot :)

**Comment by DJCALIEND** [comment]
Hum I have another bug FoxDB.Conventions exception when I want to go to settings

**Comment by aidan-g** [comment]
`/// <summary>
/// Factory method for PluralizationService. Only support english pluralization.
/// Please set the PluralizationService on the System.Data.Entity.Design.EntityModelSchemaGenerator
/// to extend the service to other locales.
/// </summary>
/// <param name="culture">CultureInfo</param>
/// <returns>PluralizationService</returns>
public static PluralizationService CreateService(CultureInfo culture)
{
    if (culture.TwoLetterISOLanguageName == "en")
    {
        return new EnglishPluralizationService();
    }
    else
    {
        throw new NotImplementedException();
    }
}`

Microsoft :(

**Comment by aidan-g** [comment]
Try replacing your FoxDb.Core.dll with this one

[FoxDb.Core.zip](https://github.com/aidan-g/FoxTunes/files/3998356/FoxDb.Core.zip)

**Comment by DJCALIEND** [comment]
You rock 👍 👍. Bug fixed. Thank you. I continue to test...

**Comment by aidan-g** [comment]
It will take a little while to update the release packages as I will need to publish the change to that library.

**Comment by DJCALIEND** [comment]
Ok. If another bug is found I update this ticket. Have a nice Christmas.

**Comment by aidan-g** [comment]
Fixed since 2.0.8 (d4ab7d9cf7565358f32e3db9bbd5f849da318f66)
