### ISSUE TITLE
Lyric in the right panel

### ISSUE THREAD

**Issue by DJCALIEND** [aidan-g/FoxTunes#43]
Hi 

Your software is perfect I love It. Thanks a lot :) Do you have a paypal account ?
Please add lyrics to the right panel. And I have problems to have lyrics columns ?

Regards 
Marc

**Comment by DJCALIEND** [comment]
and please add ratings columns :)

**Comment by aidan-g** [comment]
Regarding lyrics, if you know if a free api that can provide them I'm happy to add that functionality.

Could you please raise seperate issues for bpm and ratings?

I may add a donation link at some point, but thank you.

**Comment by DJCALIEND** [comment]
I just want to show embedded lyrics not to retrieve lyrics.

**Comment by aidan-g** [comment]
Can you provide a sample with embedded lyrics? I've never heard of this.

**Comment by aidan-g** [comment]
Available since 105c55b3d6d26999f829862dddd19264d9409bb3.
The Meta Data\Lyrics setting must be enabled before tracks are added to the library.

An issue was raised to support toggling settings like this: https://github.com/aidan-g/FoxTunes/issues/46
