### ISSUE TITLE
Beatsperminute column problem

### ISSUE THREAD

**Issue by DJCALIEND** [aidan-g/FoxTunes#44]
I have a problem to have Beatsperminute column!!!

(function () {
    var parts = [tag.BeatsPerMinute || "No BPM"];
    return parts.join(" - ");
})()

**Comment by aidan-g** [comment]
It looks like taglib supports this property so it should just be a matter of adding the mapping to TagLibMetaDataSource. I’ll look into it.

**Comment by aidan-g** [comment]
I've checked many files and although taglib supports beats per minute, it never contains a value. Can you provide an example file?

**Comment by aidan-g** [comment]
The BPM playlist column is available as of f744715f9375dbaca5eca60aca28c6332a8b51b7 but needs to be enabled in the settings. 

I did manage to find some tracks but this tag seems very rare.. It would be possible to calculate it but this would require quite a lot of work. We would have to bring up the audio engine in another process (as only a single instance is allowed per process and we need one for playback) and use BASS FX to determine the beats per minute. I don't plan implement this any time soon.
