### ISSUE TITLE
Add ratings

### ISSUE THREAD

**Issue by DJCALIEND** [aidan-g/FoxTunes#45]
Please add songs ratings :)

**Comment by aidan-g** [comment]
I've started development of this feature.
Enable the rating/play count (they're both part of "popularimeter") in meta data settings before importing tracks to use it.

There is a library context menu;

![LIbraryRating](https://user-images.githubusercontent.com/13859177/74485737-51feff80-4eb3-11ea-9e54-99d02ea636a4.PNG)

And a playlist column plugin (enabled separately in playlist settings);

![PlaylistRating](https://user-images.githubusercontent.com/13859177/74485749-5b886780-4eb3-11ea-906e-aa65777d85a7.PNG)

Be careful with this for now, it may damage your music files.

**Comment by aidan-g** [comment]
I'm trying to think of a way to filter the library based on ratings. 
Maybe entering 5* or something into the search box?

**Comment by aidan-g** [comment]
Search now supports 0-5*. Can be combined with other terms eg "year:199 5*" or "pop 5*"
