### ISSUE TITLE
Fix ratings

### ISSUE THREAD

**Issue by DJCALIEND** [aidan-g/FoxTunes#55]
Some song does not show up ratings when library is scanned for the first time.

**Comment by aidan-g** [comment]
Can you please post some sample files?

**Comment by DJCALIEND** [comment]
How can I do post a file ?

**Comment by DJCALIEND** [comment]
[Alain Souchon - C'est Deja Ca.zip](https://github.com/aidan-g/FoxTunes/files/4444737/Alain.Souchon.-.C.est.Deja.Ca.zip)

**Comment by DJCALIEND** [comment]
[Abba - Dancing Queen.zip](https://github.com/aidan-g/FoxTunes/files/4444777/Abba.-.Dancing.Queen.zip)

**Comment by DJCALIEND** [comment]
If you want more files tell me.

**Comment by aidan-g** [comment]
It appears to have an invalid rating value of 204. What rating do you expect?

Ratings as I understand them should be;
0 - unrated
1 - 1 star
64 - 2 stars
128 - 3 stars
196 - 4 stars
255 - 5 stars

There are concepts like "half stars" but there's no standard for them.

**Comment by DJCALIEND** [comment]
hum I don't know why 204 is here. MusicBee show me 4 stars and there is an option to desactivate half stars (activated for me).

**Comment by DJCALIEND** [comment]
Well so after to click to 4 stars again tag is well updated and show me 196 in the tag inspector. Arf I have to check my entire library.

**Comment by DJCALIEND** [comment]
Thanks again you can close this ticket

**Comment by aidan-g** [comment]
It looks like media monkey (and maybe other programs) use a different format. https://www.mediamonkey.com/forum/viewtopic.php?t=40532

I will update the parser to import that format. Ratings will still be written in the "windows" style (1,64,128,196,255) though as it appears to be the most popular.

**Comment by aidan-g** [comment]
> Thanks again you can close this ticket

I will add read support for that rating format under this issue.

**Comment by aidan-g** [comment]
Fixed since 01d0d56d5c654ac8cda0796a29bb1b5fd4fd14eb.
