### ISSUE TITLE
Be able to delete a song (file) after confirmation of course

### ISSUE THREAD

**Issue by DJCALIEND** [aidan-g/FoxTunes#59]

**Comment by DJCALIEND** [comment]
So I have seen you have a function to remove a file but I have never use this function because I don't know if is for to remove from library or for the life. Never tested or bad interpretation.

**Comment by aidan-g** [comment]
The Remove menu just removes from the playlist, nothing more. 

I'm not really comfortable deleting files, you could use the Locate menu to open the track in Windows and delete it that way.
