### ISSUE TITLE
Implement Play/Pause toggle. One button for Play/Pause.

### ISSUE THREAD

**Issue by DJCALIEND** [aidan-g/FoxTunes#60]

**Comment by DJCALIEND** [comment]
If you want of course :)

**Comment by aidan-g** [comment]
Alt+Space will toggle play/pause but I agree that it should be one button.

**Comment by aidan-g** [comment]
Implemented since 6e4c63675ec8ac5ecc9ae900bf279ae9e91a8de6.
![PlayPause](https://user-images.githubusercontent.com/13859177/80266302-04f98f80-8693-11ea-880d-ed818faa065a.gif)
