### ISSUE TITLE
Add Replay Gain scanner functionality.

### ISSUE THREAD

**Issue by aidan-g** [aidan-g/FoxTunes#61]

**Comment by aidan-g** [comment]
The native part of this is working although quite slow for some reason.
See the project here: https://github.com/aidan-g/BASS_REPLAY_GAIN

Hopefully will have some integration done soon.

**Comment by aidan-g** [comment]
Test build;
[FoxTunes-2020-04-15-nightly-net461.zip](https://github.com/aidan-g/FoxTunes/files/4484073/FoxTunes-2020-04-15-nightly-net461.zip)

**Comment by DJCALIEND** [comment]
+1000. WOW you are so quick :). Scanner seems to be working. Is missing tag.replaygaintrack and/or tag.replaygainalbum column(s) to see values. I need to compare with another program and "Platinum Notes" to tell you if all is ok. Thanks a lot again and take care of you.

**Comment by DJCALIEND** [comment]
Sorry I have seen tag.replaygaintrackgain.

**Comment by aidan-g** [comment]
We are using the math from libavfilter. The results are the same as what ffmpeg or vlc would generate.
I was using this command to validate;
`ffmpeg.exe -i "C:\test.mp3" -filter_complex [0:a]asplit=2:outputs=2[s0][s1];[s0]aformat=channel_layouts=stereo:sample_fmts=s16[s2];[s2]replaygain[s3];[s1]aformat=channel_layouts=stereo:sample_fmts=s16:sample_rates=48000[s4];[s4]afifo[s5];[s5]ebur128=framelog=verbose[s6] -map [s3] -map [s6] -f null nul`

You see something like;
```
[Parsed_replaygain_2 @ 017dee40] track_gain = -3.58 dB
[Parsed_replaygain_2 @ 017dee40] track_peak = 0.980347
```

I'm not very good at javascript but something like this should work;
```
(function () {
    var gain = tag.replaygaintrackgain;
    if (!gain) {
        return "None";
    }
    return parseFloat(gain).toFixed(2) + "dB";
})()
```

I will add the columns when I get time.

**Comment by aidan-g** [comment]
Test build;
[FoxTunes-2020-04-16-nightly-net461.zip](https://github.com/aidan-g/FoxTunes/files/4488685/FoxTunes-2020-04-16-nightly-net461.zip)

**Comment by aidan-g** [comment]
Test build;
[FoxTunes-2020-04-16-nightly-net461.zip](https://github.com/aidan-g/FoxTunes/files/4489860/FoxTunes-2020-04-16-nightly-net461.zip)

**Comment by aidan-g** [comment]
Added playlist columns and fixed some bugs.
Still failing sometimes, not sure why.

Test build;
[FoxTunes-2.1.4-net461.zip](https://github.com/aidan-g/FoxTunes/files/4489992/FoxTunes-2.1.4-net461.zip)

**Comment by aidan-g** [comment]
I think everything is working now;

Test build;
[FoxTunes-2020-04-18-nightly-net461.zip](https://github.com/aidan-g/FoxTunes/files/4496715/FoxTunes-2020-04-18-nightly-net461.zip)

**Comment by DJCALIEND** [comment]
I will test this tomorrow. Thank you anyway.

**Comment by DJCALIEND** [comment]
Decimal value for track gain column is always 00. (For example 7.64 show me 7.00dB)

**Comment by aidan-g** [comment]
Do you mean that it isn't returning the decimals when it should be or that you would rather not see the decimals?

I copied some other players;
![Gain](https://user-images.githubusercontent.com/13859177/79698955-266a0e00-8284-11ea-81f5-59f547ad5203.PNG)

If you don't want to see the decimals change the script;
```diff
-return (parsed > 0 ? "+" : "") + parsed.toFixed(2) + "dB";
+return (parsed > 0 ? "+" : "") + parsed.toFixed(0) + "dB";
```
