### ISSUE TITLE
Promote FoxTunes on Softpedia and others download platforms...

### ISSUE THREAD

**Issue by DJCALIEND** [aidan-g/FoxTunes#63]
Because your soft is growing and very good.

**Comment by DJCALIEND** [comment]
Hum !!! Seems to be already done. On Softpedia FoxTunes is under 'portable apps'  since long time ago (I never saw it except yesterday during a research). I close this ticket.

**Comment by aidan-g** [comment]
Yeah, looks like it's sort of up to date. Looks like the reviewed version was quite old though.
The SEO could be better too.
