### ISSUE TITLE
Make a toggle button for shuffle

### ISSUE THREAD

**Issue by DJCALIEND** [aidan-g/FoxTunes#67]
I think it's more practical than going back to the settings.

**Comment by aidan-g** [comment]
You can right click the playback buttons, I agree that a button would be better. I’ll look into it.

**Comment by DJCALIEND** [comment]
Arf I had not seen the functionality before. In any case a BIG congratulation for your software.

**Comment by aidan-g** [comment]
Can you make a graphic for the button? In `<PathGeometry/>` format. I think you can use a program like inkskape: http://www.software-architects.com/devblog/2008/01/13/Graphic-In-XAML-And-WPF

**Comment by aidan-g** [comment]
Which icon do you think looks best?

![shuffle](https://user-images.githubusercontent.com/13859177/84148448-ec80e100-aa56-11ea-8f3a-d45c51c55932.png)

![shuffle_alt](https://user-images.githubusercontent.com/13859177/84148457-ef7bd180-aa56-11ea-8b10-f3f88734098e.png)

**Comment by DJCALIEND** [comment]
The first

**Comment by aidan-g** [comment]
Implemented since 8eea40dd767bf079679a82b7d79d499c001b7ed2.
