### ISSUE TITLE
Skip silence at beginning and ending

### ISSUE THREAD

**Issue by DJCALIEND** [aidan-g/FoxTunes#68]
Between song. I think a fader will be welcome.

**Comment by aidan-g** [comment]
Detecting and skipping silence is possible (for most types of stream) but cross fading is more complicated. Raise that as a new issue.

**Comment by aidan-g** [comment]
Please post some sample files and the time that should be skipped.

**Comment by aidan-g** [comment]
Here is a test build, the setting is Output\Advanced\Skip Silence.

[FoxTunes-2020-06-09-nightly-net461-x64.zip](https://github.com/aidan-g/FoxTunes/files/4755193/FoxTunes-2020-06-09-nightly-net461-x64.zip)

It only skips true digital silence but I'm thinking of adding a threshold option.

**Comment by aidan-g** [comment]
There's no real silence there, the tracks just fade out but there's still detail right at the end.

I've come up with an algorithm that kind of works, we look at the samples until we encounter a period (some number of samples) where a consecutive number of samples have a power greater than some threshold. It's very naive though.. To work properly we would need to use IIR filters to better determine the real audible volume.

**Comment by aidan-g** [comment]
How is this? There is a setting to control what noise level is considered silent.

[FoxTunes-2020-06-12-nightly-net461-x64.zip](https://github.com/aidan-g/FoxTunes/files/4772161/FoxTunes-2020-06-12-nightly-net461-x64.zip)

1. High = -1000dB. (digital silence)
2. Medium = -60dB
3. Low = -40dB

**Comment by DJCALIEND** [comment]
It's clearly good. 

I have tested with new musics and its perfect with the medium choice and more aggressive with the low choice. 

Perfect for me. 

You rock !!!! +10000² :)

**Comment by aidan-g** [comment]
Cool. I just need to make it save the information so it doesn't get calculated every time.

**Comment by aidan-g** [comment]
Implemented since 44c86b97c363f23d2e5abde12e642430fa49a497.
