### ISSUE TITLE
Implement cross fading

### ISSUE THREAD

**Issue by DJCALIEND** [aidan-g/FoxTunes#70]

**Comment by aidan-g** [comment]
We need a new output pipleline input for this, cross fade behaviour is very different from the gapless input we're currently using. 

A new repo was created: https://github.com/aidan-g/BASS_CROSSFADE

**Comment by DJCALIEND** [comment]
Take time for this functionality. It's not in a hurry. If you want to improve/add others things before it's OK (even in 5 years :) it's perfect)

**Comment by aidan-g** [comment]
Here is a build, there are some problems like rapidly skipping tracks and stopping/starting can crash.
Select the crossfade transport;

![Crossfade_Setup](https://user-images.githubusercontent.com/13859177/85454421-d31e7f80-b594-11ea-9b80-f55dbb312d02.png)

There are some settings. The defaults are similar to foobar2k.

![Crossfade_Settings](https://user-images.githubusercontent.com/13859177/85454476-e4678c00-b594-11ea-9f3f-87f5ec4d0049.png)

Mode;
1) Manual - Only fade when making manual track changes.
2) Always - Fade all the time.

Periods in milliseconds;
1) Fade in - Volume ramp up.
2) Fade out - Volume ramp down.
3) Overlap - Cross fade time. 0 = Fade out then fade in. (NOT YET WORKING)

Curves:
Different volume curve formulas. I will create some plot data.

[FoxTunes-2020-06-23-nightly-net461-x86.zip](https://github.com/aidan-g/FoxTunes/files/4821620/FoxTunes-2020-06-23-nightly-net461-x86.zip)

**Comment by DJCALIEND** [comment]
I'm really impressed. This part was not really easy. Coded in 5 days, it is a feat.

I am waiting the overlap functionality and bugs fixing you have mentionned but you are on the right way.

I have some glitchs with smart playlist (5* for example) because the next song is not always played automaticaly when I am with 'always' mode but I need to test more. 

This WIeek End I will have more time to generate a rapport.

**Comment by aidan-g** [comment]
Should be more reliable now.

Here are the volume curves, they're all pretty similar looking.. The math is probably wrong, I'm not very good at it;

[VolumeCurves.xlsx](https://github.com/aidan-g/FoxTunes/files/4833270/VolumeCurves.xlsx)

It's generated by https://github.com/aidan-g/BASS_CROSSFADE/blob/master/bass_crossfade/crossfade_envelope.c

I can't find many examples of how to do this and even less in floating point notion..

[FoxTunes-2020-06-25-nightly-net461-x86.zip](https://github.com/aidan-g/FoxTunes/files/4833287/FoxTunes-2020-06-25-nightly-net461-x86.zip)

**Comment by aidan-g** [comment]
I had to remove the overlap time setting it was making the code too complicated unfortunately. It also didn’t seem to make sense in some situations.

**Comment by DJCALIEND** [comment]
I have 'skip silence' disabled in the settings but I always see 'skip silence' when I pass the mouse over the setting icon (crossafe is activated too) . 

I think is for that I don't hear crossfade (linear mode for now). Because 'skip silence' is still activated.

Do you confirm ?

**Comment by DJCALIEND** [comment]
Ok 'linear' mode is functional (with skip silence activated) but I have to put 'fade out/fade in' cursors minimum in the middle to hear the crossfade.

Could you put a text which show how long is the period for fade in/ fade out int he settings view when we move cursors ?

**Comment by aidan-g** [comment]
there seems to be a bug with skip silence, it doesn't switch off properly. you're right that you'll need the sliders around 1500-2000 to really hear it, the default is only 100ms (1/10th of a second) which is hardly notifiable. I just coped foobar as that's really the gold standard.

<img width="298" alt="FooFading" src="https://user-images.githubusercontent.com/13859177/85803364-de151380-b73e-11ea-841e-d73c95d37863.PNG">

I'll look into the skip silence and tooltip thing.

**Comment by aidan-g** [comment]
Fixed silence bug.
There is a tooltip if you hover over the slider in the settings window, 1000 = 1 second.

![SliderTooltip](https://user-images.githubusercontent.com/13859177/85907217-a4104400-b808-11ea-9708-b49969dfbd6b.PNG)

You can also see the times in the bottom corner tooltip;

![FadingTooltip](https://user-images.githubusercontent.com/13859177/85907173-83e08500-b808-11ea-8dc7-ec5b26347213.PNG)

[FoxTunes-2020-06-26-nightly-net461-x86.zip](https://github.com/aidan-g/FoxTunes/files/4839522/FoxTunes-2020-06-26-nightly-net461-x86.zip)

**Comment by aidan-g** [comment]
Overhauled the volume curve math it looks a lot better now;

[VolumeCurves.xlsx](https://github.com/aidan-g/FoxTunes/files/4839543/VolumeCurves.xlsx)

**Comment by DJCALIEND** [comment]
So 'linear' mode is now fully functional (and very smooth) with 'fade in' = 2s and 'fade out' = 3,5s. 

I have just a windows defender warning, since you have implemented crossfade, with Windows 2004 on my Surface. Not at work with windows 1809. The warning popup disappears by itself. Popup only appear when I unzip and move downloaded FoxTunes files to my FoxTunes directory.

I am testing others curves (and tell you) but I can say a big 'BRAVO' for this functionnality. 👏 👍

**Comment by aidan-g** [comment]
Unfortunately anti virus can warn about any exe/dll that is uncommon and unsigned. 
By the way, you must delete all the old files when copying, especially settings.dat and database.db.
https://github.com/aidan-g/FoxTunes/issues/53

**Comment by DJCALIEND** [comment]
'Linear' mode is definitively my preferred. Work fine for me. So you can close this issue.

**Comment by aidan-g** [comment]
Added fade when pause/resume option. Do you think it should be switched on by default? Makes the UI a little unresponsive. 

If everything with this build is OK I will close.

[FoxTunes-2020-06-28-nightly-net461-x86.zip](https://github.com/aidan-g/FoxTunes/files/4842950/FoxTunes-2020-06-28-nightly-net461-x86.zip)

**Comment by DJCALIEND** [comment]
I think you should leave it 'not checked' by default.

Is missing perhaps no fade when you stop playing.

Otherwise everything is perfect for me.

**Comment by DJCALIEND** [comment]
Two last minutes glitches:
- When you stop playing sound is amplified (when fading activated)
- When you desactivate 'Skip silence' when playing 'skip silence' is always here.

**Comment by aidan-g** [comment]
I’ll look into the amplification but toggling the silence while playing is not possible unfortunately. The length of the stream can not be changed once it has started playing.

**Comment by DJCALIEND** [comment]
It's not important. Leave like this (at least for me).

**Comment by aidan-g** [comment]
I wasn't able to reproduce sound amplified but I have re-written the fade out when stopping so might have already fixed it.
Can you re test with this version and if it is still broken then post the audio files and your Settings.dat 
Make sure to save the settings with the new version first.

[FoxTunes-2020-06-30-nightly-net461-x86.zip](https://github.com/aidan-g/FoxTunes/files/4851132/FoxTunes-2020-06-30-nightly-net461-x86.zip)

PS: If you see an error regarding Silence SetPosition I'm aware of it.

**Comment by DJCALIEND** [comment]
I have no more sound amplified when I stop playing (fade to stop actived). Cool 👍

**Comment by DJCALIEND** [comment]
Is 'Skip silence' functional when crossafe is actif ? It does not seem..

**Comment by DJCALIEND** [comment]
So I use now 'OUT EXPO' curve for in/out and it's very good (with 2500ms for fade in/out). Very good job 👍

**Comment by aidan-g** [comment]
There are some conflicts between the features, I think it is a race condition. I haven't looked into it yet. 

The curve math is quite interesting, I'm thinking of adding a S curve also. It seems popular in mixing to use an fade in = out exponential and fade in = linear. Looks like this;

![Fade](https://user-images.githubusercontent.com/13859177/86156641-301eb600-bafe-11ea-9588-9fd7ef007175.PNG)

I'm not sure I can hear a difference between them personally haha

**Comment by DJCALIEND** [comment]
Let's try !!! Why not ? I bought recently a Surface Headphone 2 and now I hear the difference. (Do you want one ? It's free of course)

**Comment by aidan-g** [comment]
This is a nice site for visualizing them https://easings.net/
We really need to replace the "mix" checkbox with a real "overlap" slider but the code was confusing for me. 
If you have an overlap of 1000ms and fade in of 500ms and fade out of 750ms.... And then press the next button, what should happen??? It hurts my brain.

That headphone looks quite nice, although expensive, I actually have a surface laptop 2 for development. It's a good machine.

**Comment by aidan-g** [comment]
It seems logically that the overlap is unbounded and could even be a negative number. Tricky.

**Comment by DJCALIEND** [comment]
Your coding skill is exceptional. Never saw it before. So If you want  I send you the amount to buy a Surface Hearphone 2. It's my little contribution your great software and the amount of time you passed.

**Comment by DJCALIEND** [comment]
For the rest we can put this functionality as experimental and when we have finished to test it will be available for all.

**Comment by aidan-g** [comment]
Ah, well thank you very much. I can email my postal address if you like?

**Comment by DJCALIEND** [comment]
Ok I send you the amount but for a Surface Headphone 2 of course :).. We can have Teamviewer/Teams/Skype conversations if you want when we meet bugs It's more simple than wrote a text.

**Comment by DJCALIEND** [comment]
So Livre Sterling/Euro conversion is quite difficult. Hope the amount is here.

**Comment by aidan-g** [comment]
Yeah I got it, thanks again. 

Implemented since 39dc3658b06bcfd9faeeefc65d87052def84fd75.
