### ISSUE TITLE
Implement a new wave bar

### ISSUE THREAD

**Issue by DJCALIEND** [aidan-g/FoxTunes#75]
![Wave Bar](https://user-images.githubusercontent.com/4847909/87880625-6c558000-c9f3-11ea-872f-3cec8c34780a.png)

**Comment by aidan-g** [comment]
What does the wave form represent? Amplitude or some kind of frequency information?

**Comment by DJCALIEND** [comment]
For me it's the amplitude (height of the wave). Frequency is for the pitch/speed (the longer the wavelength, the lower the pitch).

**Comment by aidan-g** [comment]
Implemented as of e3865b95ed34122c78dfc0f50e711c9a273e3954.

![HhbB8gbj7F](https://user-images.githubusercontent.com/13859177/90344751-927f3780-e014-11ea-9d58-eae9e69f880b.gif)

We need to create a wiki article on how to use the plugin.
