### ISSUE TITLE
Be able to sort columns (ascending/descending) in the playlist.

### ISSUE THREAD

**Issue by DJCALIEND** [aidan-g/FoxTunes#86]

**Comment by aidan-g** [comment]
This is long overdue but blocked by some other issues; #87 and #88.

Once we know if the column is a script or simple meta data we can sort in SQL for performance or fall back to in memory for script columns. 

Sorting on non trivial columns will likely be disabled by default as it would require pulling lots of data into ram.

**Comment by aidan-g** [comment]
Implemented since 6abd152fc09ff99ed2bb44e556ce616803f62079
