### ISSUE TITLE
Lyrics download is not implemented.

### ISSUE THREAD

**Issue by aidan-g** [aidan-g/FoxTunes#96]
I was unable to find a free API for downloading lyrics, if anybody knows of one I will implement this feature.

**Comment by tyzmodo** [comment]
hello,how about chartlyrics(www.chartlyrics.com)?

**Comment by aidan-g** [comment]
> 
> 
> hello,how about chartlyrics([www.chartlyrics.com](http://www.chartlyrics.com))?

Thank you, I will look into it.

**Comment by aidan-g** [comment]
Manual lookup added in a9d548a22f2e053a047c473cb4e85ce95b3e4da2.

To do;

1) Add minimum confidence settings. The API returns matches which are obviously incorrect.
2) Implement automatic lookup. There is a already a setting for this.
3) Prompt the user to pick a result when there are multiple "good" matches. We're currently picking the highest rated result.

**Comment by aidan-g** [comment]
Implemented since 7baff0cb989cc4463da52bc897415b4c12e67bfc.
